function updateCountry()
    {
    const phoneInput=document.getElementById("telephone");
    const countryCode=phoneInput.value.split(' ')[0].trim();
    const countrySelect= document.getElementById("codepays");
    const countryCodes={
        "+93": "Afghanistan",
        "+355": "Albanie",
        "+213": "Algérie",
        "+376": "Andorre",
        "+244": "Angola",
        "+54": "Argentine",
        "+374": "Arménie",
        "+61": "Australie",
        "+43": "Autriche",
        "+994": "Azerbaidjan",
        "+973": "Bahrein",
        "+880": "Bangladesh",
        "+375": "Biélorussie",
        "+32": "Belgique",
        "+501": "Belize",
        "+229": "Bénin",
        "+975": "Bhoutan",
        "+591": "Bolivie",
        "+387": "Bosnie-Herzégovine",
        "+267": "Bostwana",
        "+55": "Brésil",
        "+673": "Brunei",
        "+359": "Bulgarie",
        "+226": "Burkina Faso",
        "+257": "Burundi",
        "+855": "Cambodge",
        "+237": "Cameroun",
        "+1": "Canada",
        "+238": "Cap-Vert",
        "+236": "République centrafricaine",
        "+235": "Tchad",
        "+56": "Chili",
        "+86": "Chine",
        "+57": "Colombie",
        "+269": "Comores",
        "+242": "République du Congo",
        "+243": "République démocratique du Congo",
        "+682": "îles Cook",
        "+506": "Costa Rica",
        "+385": "Croatie",
        "+53": "Cuba",
        "+357": "Chypre",
        "+420": "République tchèque",
        "+45": "Danemark",
        "+253": "Djibouti",
        "+670": "Timor oriental",
        "+593": "Equateur",
        "+20": "Egypte",
        "+503": "El Salvador",
        "+240": "Guinée équatoriale",
        "+291": "Erythrée",
        "+372": "Estonie",
        "+251": "Ethiopie",
        "+679": "Fidji",
        "+358": "Finlande",
        "+33": "France",
        "+241": "Gabon",
        "+220": "Gambie",
        "+995": "Géorgie",
        "+49": "Allemagne",
        "+233": "Ghana",
        "+30": "Grèce",
        "+299": "Groenland",
        "+502": "Guatemala",
        "+224": "Guinée",
        "+245": "Guinée-Bissau",
        "+592": "Guyana",
        "+509": "Haïti",
        "+504": "Honduras",
        "+36": "Hongrie",
        "+354": "Islande",
        "+91": "Inde",
        "+62": "Indonésie",
        "+98": "Iran",
        "+964": "Irak",
        "+353": "Irlande",
        "+972": "Israël",
        "+39": "Italie",
        "+225": "Côte d'ivoire",
        "+81": "Japon",
        "+962": "Jordanie",
        "+7": "Kazakhstan",
        "+254": "Kenya",
        "+686": "Kiribati",
        "+965": "Koweït",
        "+996": "Kirghizistan",
        "+856": "Laos",
        "+371": "Lettonie",
        "+961": "Liban",
        "+266": "Lesotho",
        "+231": "Libéria",
        "+218": "Libye",
        "+423": "Liechtenstein",
        "+370": "Lituanie",
        "+352": "Luxembourg",
        "+261": "Madagascar",
        "+265": "Malawi",
        "+60": "Malaisie",
        "+960": "Maldives",
        "+223": "Mali",
        "+356": "Malte",
        "+692": "Îles Marshall",
        "+222": "Mauritanie",
        "+230": "Maurice",
        "+52": "Mexique",
        "+691": "Micronésie",
        "+373": "Moldavie",
        "+377": "Monaco",
        "+976": "Mongolie",
        "+382": "Monténégro",
        "+212": "Maroc",
        "+258": "Mozambique",
        "+264": "Namibie",
        "+674": "Nauru",
        "+977": "Népal",
        "+31": "Pays-Bas",
        "+64": "Nouvelle-Zélande",
        "+505": "Nicaragua",
        "+227": "Niger",
        "+234": "Nigéria",
        "+47": "Norvège",
        "+968": "Oman",
        "+92": "Pakistan",
        "+680": "Palaos",
        "+507": "Panama",
        "+675": "Papouasie-Nouvelle-Guinée",
        "+595": "Paraguay",
        "+51": "Pérou",
        "+63":"Philippines",
        "+48":"Pologne",
        "+351": "Portugal",
        "+974": "Quatar",
        "+262": "Réunion",
        "+40": "Roumanie",
        "+7": "Russie",
        "+250": "Rwanda",
        "+685": "Samoa",
        "+378": "Saint-Marin",
        "+239": "Sao Tomé-et-Principe",
        "+966": "Arabie saoudite",
        "+221": "Sénégal",
        "+381": "Serbie",
        "+248": "Seychelles",
        "+232": "Sierra leone",
        "+65": "Singapour",
        "+421": "Slovaquie",
        "+386": "Slovénie",
        "+677": "Îles Salomon",
        "+252": "Somalie",
        "+27": "Afrique du Sud",
        "+82": "Corée du Sud",
        "+211": "Soudan du Sud",
        "+34": "Espagne", 
        "+94": "Srilanka",
        "+249": "Soudan",
        "+597": "Suriname",
        "+268": "Eswatini",
        "+46": "Suède",
        "+41": "Suisse",
        "+963": "Syrie",
        "+886": "Taïwan",
        "+992": "Tadjikistan",
        "+255": "Tanzanie",
        "+66": "Thaïlande",
        "+228": "Togo",
        "+676": "Tonga",
        "+216": "Tunisie",
        "+90": "Turquie",
        "+993": "Turkménistan",
        "+688": "Tuvalu",
        "+256": "Ouganda",
        "+380": "Ukraine",
        "+971": "Emirats arabes unis",
        "+44": "Royaume-Uni",
        "+1": "Etats-Unis/Canada",
        "+598": "Uruguay",
        "+998": "Ouzbékistan",
        "+678": "Vanuatu",
        "+58": "Venezuela",
 
    };
    if (countryCodes[countryCode]){
        countrySelect.value=countryCode;
    }
    else{
        countrySelect.value="";
    }

    if(countrySelect.value=countryCode){
        countryCodes[countryCode]
    }
}